version: "3.9"

services:
  mongo_chatbot:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ROOTchatbot
      MONGO_INITDB_ROOT_PASSWORD: ROOTchatbot
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo_chatbot:/data/db

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://ROOTchatbot:ROOTchatbot@mongo_chatbot:27017/founder-bot?authSource=admin
    depends_on:
      - mongo_chatbot
